### PR TITLE
Explain other values for g:peekaboo_window

### PR DESCRIPTION
**Pull request by fflorent**
This Pull Request explains the other values for g:peekaboo_window.

Nice plugin by the way!

Florent

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks for your suggestion. It's a very good description of the possible options. But please understand that I want to keep the README page super-short as it is now. It's a personal obsession of mine.

**Comment by fflorent** [comment]
OK, but could you at least refer to the other possibilities (the two links to vimdoc)? So it would be friendlier for people that are not so used to vim.

FWIW, I had to search for documentation to understand how to change this variable.

Florent

**Comment by junegunn** [comment]
The decision was the result of personal taste, and not a rational one :)

Yes, you're perfectly right that it's going to be helpful for the users without enough experience. But on the flip side, the seasoned users should have no problem understanding the option and may feel that the extra explanation is stating the obvious.

**Comment by Doron-Behar** [comment]
I agree with @fflorent on that, I downloaded the plugin and was really impressed, it's exactly what I was looking for. After a while I wanted to change this setting as well and was lucky enough to find this issue rather quickly so perhaps you could add a `doc/peekaboo.txt` help file so it would be easier for others as well?

**Pull request closed without merging**
